version: "3.9"

services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: couriertrackingdatabase
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - couriertrackingNetwork


  couriertrackingexample:
    image: 'couriertrackingexample:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: couriertrackingexample
    restart: on-failure
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "1231:1231"
    environment:
      - server.port=1231
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - COURIRER_TRACKING_DB_IP=database
      - COURIRER_TRACKING_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/couriertrackingdatabase
    volumes:
      - ./resources/stores.json:/stores.json
    depends_on:
      - database
    networks:
      - couriertrackingNetwork

networks:
  couriertrackingNetwork: